<?php

namespace Proxies\__CG__\Bontekoe\CinemaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cinema extends \Bontekoe\CinemaBundle\Entity\Cinema implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Cinema' . "\0" . 'showschema', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Cinema' . "\0" . 'id', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Cinema' . "\0" . 'number', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Cinema' . "\0" . 'rows', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Cinema' . "\0" . 'rowSeats');
        }

        return array('__isInitialized__', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Cinema' . "\0" . 'showschema', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Cinema' . "\0" . 'id', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Cinema' . "\0" . 'number', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Cinema' . "\0" . 'rows', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Cinema' . "\0" . 'rowSeats');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cinema $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', array($number));

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', array());

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setRows($rows)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRows', array($rows));

        return parent::setRows($rows);
    }

    /**
     * {@inheritDoc}
     */
    public function getRows()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRows', array());

        return parent::getRows();
    }

    /**
     * {@inheritDoc}
     */
    public function setRowSeats($rowSeats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRowSeats', array($rowSeats));

        return parent::setRowSeats($rowSeats);
    }

    /**
     * {@inheritDoc}
     */
    public function getRowSeats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRowSeats', array());

        return parent::getRowSeats();
    }

    /**
     * {@inheritDoc}
     */
    public function addShow(\Bontekoe\CinemaBundle\Entity\Showschema $show)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addShow', array($show));

        return parent::addShow($show);
    }

    /**
     * {@inheritDoc}
     */
    public function removeShow(\Bontekoe\CinemaBundle\Entity\Showschema $show)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeShow', array($show));

        return parent::removeShow($show);
    }

    /**
     * {@inheritDoc}
     */
    public function getShows()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShows', array());

        return parent::getShows();
    }

    /**
     * {@inheritDoc}
     */
    public function addShowschema(\Bontekoe\CinemaBundle\Entity\Showschema $showschema)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addShowschema', array($showschema));

        return parent::addShowschema($showschema);
    }

    /**
     * {@inheritDoc}
     */
    public function removeShowschema(\Bontekoe\CinemaBundle\Entity\Showschema $showschema)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeShowschema', array($showschema));

        return parent::removeShowschema($showschema);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowschema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowschema', array());

        return parent::getShowschema();
    }

}
