<?php

namespace Proxies\__CG__\Bontekoe\CinemaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservation extends \Bontekoe\CinemaBundle\Entity\Reservation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'showschema', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'user', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'id', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'row', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'rowSeat', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'paid', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'type', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'showschemaId', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'userId');
        }

        return array('__isInitialized__', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'showschema', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'user', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'id', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'row', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'rowSeat', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'paid', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'type', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'showschemaId', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Reservation' . "\0" . 'userId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reservation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRow($row)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRow', array($row));

        return parent::setRow($row);
    }

    /**
     * {@inheritDoc}
     */
    public function getRow()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRow', array());

        return parent::getRow();
    }

    /**
     * {@inheritDoc}
     */
    public function setRowSeat($rowSeat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRowSeat', array($rowSeat));

        return parent::setRowSeat($rowSeat);
    }

    /**
     * {@inheritDoc}
     */
    public function getRowSeat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRowSeat', array());

        return parent::getRowSeat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaid($paid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaid', array($paid));

        return parent::setPaid($paid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaid', array());

        return parent::getPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowschemaId($showschemaId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowschemaId', array($showschemaId));

        return parent::setShowschemaId($showschemaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowschemaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowschemaId', array());

        return parent::getShowschemaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', array($userId));

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowschema(\Bontekoe\CinemaBundle\Entity\Showschema $showschema = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowschema', array($showschema));

        return parent::setShowschema($showschema);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowschema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowschema', array());

        return parent::getShowschema();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Bontekoe\CinemaBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

}
