<?php

namespace Proxies\__CG__\Bontekoe\CinemaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Showschema extends \Bontekoe\CinemaBundle\Entity\Showschema implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'cinema', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'movie', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'reservation', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'id', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'cinemaId', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'movieId', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'datetime');
        }

        return array('__isInitialized__', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'cinema', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'movie', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'reservation', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'id', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'cinemaId', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'movieId', '' . "\0" . 'Bontekoe\\CinemaBundle\\Entity\\Showschema' . "\0" . 'datetime');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Showschema $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCinemaId($cinemaId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCinemaId', array($cinemaId));

        return parent::setCinemaId($cinemaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCinemaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCinemaId', array());

        return parent::getCinemaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMovieId($movieId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMovieId', array($movieId));

        return parent::setMovieId($movieId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovieId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovieId', array());

        return parent::getMovieId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatetime($datetime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatetime', array($datetime));

        return parent::setDatetime($datetime);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatetime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatetime', array());

        return parent::getDatetime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCinema(\Bontekoe\CinemaBundle\Entity\Cinema $cinema = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCinema', array($cinema));

        return parent::setCinema($cinema);
    }

    /**
     * {@inheritDoc}
     */
    public function getCinema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCinema', array());

        return parent::getCinema();
    }

    /**
     * {@inheritDoc}
     */
    public function setMovie(\Bontekoe\CinemaBundle\Entity\Movie $movie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMovie', array($movie));

        return parent::setMovie($movie);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovie', array());

        return parent::getMovie();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservation(\Bontekoe\CinemaBundle\Entity\Reservation $reservation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservation', array($reservation));

        return parent::addReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservation(\Bontekoe\CinemaBundle\Entity\Reservation $reservation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservation', array($reservation));

        return parent::removeReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservation', array());

        return parent::getReservation();
    }

}
