<?php

namespace Bontekoe\CinemaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShowschemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowschemaRepository extends EntityRepository
{
}
